name: digital_logbook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  cloud_firestore: any
  firebase_core: any
  cr_calendar: 0.0.5
  flutter_slidable: ^1.2.0
  animated_text_kit: ^4.2.1
  device_preview: ^0.7.4
  flutter_staggered_grid_view: 0.4.0
  table_calendar: ^3.0.8
  shared_preferences: ^2.0.4
  carousel_slider: ^4.0.0
  percent_indicator:  4.0.1
  google_fonts: ^2.0.0
  curved_navigation_bar: ^1.0.3
  assorted_layout_widgets: ^5.5.0
  focused_menu: ^1.0.5
  animated_theme_switcher: ^2.0.1
  open_file: ^3.2.1
  url_launcher: ^6.0.11
  intl: ^0.17.0
  datetime_picker_formfield: 2.0.0
  file_picker: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_material_color_picker: ^1.1.0+2
  mime: ^1.0.1
  firebase_storage: any
  cloud_firestore_web: any
  image_picker: any
  path: any
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  get_it: ^7.0.0
  lottie: ^1.2.2
  sizer: ^2.0.14
  flutter_downloader: ^1.7.3
  duration_picker: ^1.1.1
  universal_platform: ^1.0.0+1
  multi_stream_builder: ^0.0.1
  syncfusion_flutter_calendar: ^19.1.58
  pdf: ^3.1.0
  firebase_messaging: ^12.0.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  flutter_local_notifications: ^9.7.0
  permission_handler: 10.0.0
  flutter_picker: any
  syncfusion_flutter_charts: ^19.1.58
  dashboard: any
  flutter_colorpicker: ^1.0.3
  auto_size_text: ^3.0.0
  bubble_tab_indicator: any
  fl_chart: any
  dotted_border: ^2.0.0+1
  timeago: ^3.1.0
  eva_icons_flutter: ^3.0.2
  get: ^3.24.0
  hive: any
  hive_flutter: any
  timezone: any
  flutter_clean_calendar: ^1.1.0
  animate_do: ^2.1.0
  another_flushbar: ^1.10.28
  awesome_dialog: ^2.1.2
  bloc: any
  connectivity_plus: ^2.2.0
  date_picker_timeline: ^1.2.3
  day_night_time_picker: ^1.0.5
  equatable: ^2.0.3
  flutter_bloc: any
  awesome_notifications: ^0.6.21
  google_sign_in: ^5.2.4
  flutter_speed_dial: any
  time_range_picker : any
  time_range: ^1.1.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  flutter_icons_null_safety: ^1.1.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.2
  build_runner: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  smooth_page_indicator: ^0.3.0-nullsafety.0
  colorize_text_avatar: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  firebase_core_platform_interface: 4.5.1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo.png
    - assets/icons/
    - assets/firebase_logo.png
    - assets/icons/
    - assets/slides/
    - assets/logo/

  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight : 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300


  # fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
